"""
FastAPI application for RAG Agent API.

Exposes `/ask` endpoint for query processing with retrieval-augmented responses.
"""

import logging
import os
import time
from datetime import datetime
from typing import Optional
import uuid

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import ValidationError

from backend.src.models.chat import ChatRequest, ChatResponse, ErrorResponse, ErrorDetail
from backend.src.agent.rag_agent import RAGAgent
from backend.src.agent.orchestrator import RAGOrchestrator
from backend.src.retrieve import QueryEmbedder, QdrantRetriever, ContextExtractor

# Configure logging
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="RAG Agent API",
    description="Retrieval-Augmented Generation agent for book chatbot",
    version="0.1.0",
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Configure appropriately for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Request ID middleware
@app.middleware("http")
async def add_request_id(request: Request, call_next):
    """Add request ID to each request for tracking."""
    request_id = str(uuid.uuid4())
    request.state.request_id = request_id
    response = await call_next(request)
    response.headers["X-Request-ID"] = request_id
    return response


# Initialize components on startup
rag_orchestrator: Optional[RAGOrchestrator] = None


@app.on_event("startup")
async def startup_event():
    """Initialize RAG components on app startup."""
    global rag_orchestrator

    logger.info("Starting RAG Agent API...")

    try:
        # Load configuration from environment
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise ValueError("OPENAI_API_KEY environment variable not set")

        qdrant_url = os.getenv("QDRANT_URL", "http://localhost:6333")
        qdrant_api_key = os.getenv("QDRANT_API_KEY")
        qdrant_collection = os.getenv("QDRANT_COLLECTION", "book_embeddings")
        cohere_api_key = os.getenv("COHERE_API_KEY")

        if not cohere_api_key:
            raise ValueError("COHERE_API_KEY environment variable not set")

        # Initialize components
        logger.info("Initializing retrieval pipeline...")
        embedder = QueryEmbedder(cohere_api_key)
        retriever = QdrantRetriever(qdrant_url, qdrant_api_key, qdrant_collection)
        extractor = ContextExtractor()

        logger.info("Initializing RAG agent...")
        agent = RAGAgent(openai_api_key)

        logger.info("Initializing RAG orchestrator...")
        rag_orchestrator = RAGOrchestrator(
            embedder=embedder,
            retriever=retriever,
            agent=agent,
            extractor=extractor,
            similarity_threshold=float(os.getenv("SIMILARITY_THRESHOLD", "0.5")),
            max_context_tokens=int(os.getenv("MAX_CONTEXT_TOKENS", "6000")),
        )

        logger.info("RAG Agent API startup complete")

    except Exception as e:
        logger.error(f"Startup failed: {e}")
        raise


@app.get("/health", tags=["health"])
async def health_check():
    """Health check endpoint."""
    return {
        "status": "ok",
        "timestamp": datetime.utcnow().isoformat(),
    }


@app.get("/docs", tags=["documentation"])
async def openapi_docs():
    """OpenAPI documentation endpoint (auto-generated by FastAPI)."""
    return {"message": "Visit /docs for interactive API documentation"}


@app.post("/ask", response_model=ChatResponse, tags=["chat"])
async def ask_query(request: Request, chat_request: ChatRequest):
    """Process user query with retrieval-augmented response.

    Endpoint: POST /ask

    Request:
        {
            "query": "What is physical AI?",
            "top_k": 5,
            "similarity_threshold": 0.7,
            "user_id": "user_123"
        }

    Response:
        {
            "request_id": "uuid",
            "answer": "Physical AI refers to...",
            "sources": [...],
            "context_used": 3,
            "tokens_used": 487,
            "response_time_ms": 1850,
            "timestamp": "2025-12-12T10:30:00Z"
        }

    Args:
        request: FastAPI request object
        chat_request: Chat request with query and parameters

    Returns:
        ChatResponse with answer, sources, and metadata

    Raises:
        HTTPException: For validation errors (400), service errors (503), etc.
    """
    request_id = request.state.request_id
    start_time = time.time()

    try:
        # Validate request
        if not chat_request.query.strip():
            raise HTTPException(
                status_code=400,
                detail=ErrorResponse(
                    request_id=request_id,
                    error="Validation Error",
                    details=[ErrorDetail(field="query", message="Query cannot be empty")],
                    timestamp=datetime.utcnow().isoformat(),
                ).model_dump(),
            )

        logger.info(f"[{request_id}] Query: {chat_request.query[:50]}...")

        # Check if orchestrator initialized
        if rag_orchestrator is None:
            logger.error(f"[{request_id}] RAG orchestrator not initialized")
            raise HTTPException(
                status_code=503,
                detail=ErrorResponse(
                    request_id=request_id,
                    error="Service Unavailable",
                    details=[
                        ErrorDetail(
                            field="service",
                            message="RAG orchestrator not initialized. Check server logs.",
                        )
                    ],
                    timestamp=datetime.utcnow().isoformat(),
                ).model_dump(),
            )

        # Process query
        response = rag_orchestrator.process_query(chat_request)
        response.request_id = request_id  # Ensure consistent request_id
        response.response_time_ms = int((time.time() - start_time) * 1000)

        logger.info(
            f"[{request_id}] Response: {len(response.answer)} chars, "
            f"{response.tokens_used} tokens, {response.response_time_ms}ms, "
            f"{len(response.sources)} sources"
        )

        return response

    except ValidationError as e:
        logger.warning(f"[{request_id}] Validation error: {e}")
        errors = [
            ErrorDetail(field=err["loc"][0], message=err["msg"]) for err in e.errors()
        ]
        raise HTTPException(
            status_code=400,
            detail=ErrorResponse(
                request_id=request_id,
                error="Validation Error",
                details=errors,
                timestamp=datetime.utcnow().isoformat(),
            ).model_dump(),
        )

    except RuntimeError as e:
        logger.error(f"[{request_id}] Processing error: {e}")
        raise HTTPException(
            status_code=503,
            detail=ErrorResponse(
                request_id=request_id,
                error="Service Unavailable",
                details=[ErrorDetail(field="service", message=str(e))],
                timestamp=datetime.utcnow().isoformat(),
            ).model_dump(),
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"[{request_id}] Unexpected error: {e}")
        raise HTTPException(
            status_code=500,
            detail=ErrorResponse(
                request_id=request_id,
                error="Internal Server Error",
                details=[ErrorDetail(field="error", message="An unexpected error occurred")],
                timestamp=datetime.utcnow().isoformat(),
            ).model_dump(),
        )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "backend.src.api:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )
